# Generated by Django 3.2 on 2022-04-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('related_post', models.CharField(max_length=200, unique=True)),
                ('related_author', models.CharField(max_length=200, unique=True)),
                ('issue_type', models.IntegerField(choices=[(0, 'Post'), (1, 'Comment'), (2, 'User'), (3, 'Profile'), (4, 'Other')], default=0)),
                ('issue_details', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
